### ISSUE TITLE
This is not an Issue, but more of a question or clarification

### ISSUE THREAD

**Issue by bluedangerforyou** [treebuilder/s3-mining#1]
Hi, gotta say great tool!! Thank you for it.

My question is, when you type in the domain, example: s3.py example.com

How do you determine if this bucket actually belongs to the domain? it seems after bruteforcing, towards end, it kind of checks random bucket name.

I am a bug bounty hunter and I just want to make sure I am reporting to the correct bucket owner. As even though a bucket name may have a company name in it, it doesnt mean the company actually owns that bucket. I was wondering also if there is a way to do like a reverse cname lookup, to find the originating domain name from the cname, but thats unlikely I believe

**Comment by treebuilder** [comment]
Thank you!

There really is no way to determine S3 bucket ownership, at least in terms of determining whether a bucket named "example.com" actually belongs to the owners of the example.com domain.  The bucket names are arbitrary and on a first-come, first-served basis.

The multiple checks are attempts to find likely variants of the supplied name, since people don't always name their buckets obvious things.


In theory, the awscli s3api command "get-bucket-acl" should return the owner info, but it appears that's only accessible if you are, in fact, the bucket owner.

I've experimented with a few of the API commands, but haven't been successful (yet) in obtaining owner information.

If someone has a reliable method, I'd appreciate it if you shared it with us.
